### PR TITLE
Added my assignmet-1 notebook file to the branch assignment-1

### PR DESCRIPTION
**Pull request by hoseinaliyari**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

adding assignment file

## How were these changes tested?

tested in VSCode by running Blocks

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by dwz92 — CHANGES_REQUESTED** [review]
Logic error in both Part 1 and 2. Functions return True for cases like `print(anagram_checker("iiiiii", "listen"))`, while it is very clear that these two are not anagram of each other.

**Comment by hoseinaliyari** [comment]
@dwz92 Thanks for the feedback. I fixed it by checking both of the words over each other.

**Review by dwz92 — CHANGES_REQUESTED** [review]
your functions returns false for print(anagram_checker("night", "THING")) when these two words are anagram of each other.

**Comment by hoseinaliyari** [comment]
@dwz92 I see, the first part of my code was case sensitive, to disable this I added .lower method to this part too.

**Review by dwz92 — CHANGES_REQUESTED** [review]
For cases like (si, sii) or (ss, is), your functions returns true. But you can see they are not anagram of each other. My recommendation is using sorted() and compare. This way we know for sure the two words are anagram.

Final marking is today, please fix this asap.

**Review by dwz92 — APPROVED** [review]
Remember to remove the wrong answers. 

Approved.

**Comment by hoseinaliyari** [comment]
@dwz92 Hi Emma, I am sorry about the headache and thank you for the hint.
at the bottom part, I used your hint and also as an extra challenge I tried to fix my approach too, which I did, but there is no doubt that using "sorted" is much better.

**Pull request merged**
